FUNCTION MZM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MZM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MZM_PHY(D, PIN, POUT)
END FUNCTION MZM

FUNCTION MXF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MXF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MXF_PHY(D, PIN, POUT)
END FUNCTION MXF
FUNCTION MXF2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MXF2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL MXF2D_PHY(D, PIN, POUT)
END FUNCTION MXF2D

FUNCTION MXM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MXM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MXM_PHY(D, PIN, POUT)
END FUNCTION MXM
FUNCTION MXM2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MXM2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL MXM2D_PHY(D, PIN, POUT)
END FUNCTION MXM2D

FUNCTION MYF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MYF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MYF_PHY(D, PIN, POUT)
END FUNCTION MYF
FUNCTION MYF2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MYF2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL MYF2D_PHY(D, PIN, POUT)
END FUNCTION MYF2D

FUNCTION MYM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MYM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MYM_PHY(D, PIN, POUT)
END FUNCTION MYM
FUNCTION MYM2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MYM2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL MYM2D_PHY(D, PIN, POUT)
END FUNCTION MYM2D

FUNCTION MZF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: MZF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL MZF_PHY(D, PIN, POUT)
END FUNCTION MZF

FUNCTION DZF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DZF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DZF_PHY(D, PIN, POUT)
END FUNCTION DZF

FUNCTION DXF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DXF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DXF_PHY(D, PIN, POUT)
END FUNCTION DXF

FUNCTION DXM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DXM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DXM_PHY(D, PIN, POUT)
END FUNCTION DXM
FUNCTION DXM2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DXM2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL DXM2D_PHY(D, PIN, POUT)
END FUNCTION DXM2D

FUNCTION DYF(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DYF_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DYF_PHY(D, PIN, POUT)
END FUNCTION DYF

FUNCTION DYM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DYM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DYM_PHY(D, PIN, POUT)
END FUNCTION DYM
FUNCTION DYM2D(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DYM2D_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT) :: POUT
  CALL DYM2D_PHY(D, PIN, POUT)
END FUNCTION DYM2D

FUNCTION DZM(PIN) RESULT(POUT)
  USE MODE_SHUMAN_PHY, ONLY: DZM_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT, D%NKT), INTENT(IN) :: PIN
  REAL, DIMENSION(D%NIJT, D%NKT) :: POUT
  CALL DZM_PHY(D, PIN, POUT)
END FUNCTION DZM

FUNCTION GX_M_M(OFLAT,PA,PDXX,PDZZ,PDZX) RESULT(PGX_M_M)
  USE MODE_GRADIENT_M_PHY, ONLY: GX_M_M_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDXX
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZX
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGX_M_M
  CALL GX_M_M_PHY(D,OFLAT,PA,PDXX,PDZZ,PDZX,PGX_M_M)
END FUNCTION GX_M_M

FUNCTION GX_M_U(OFLAT,PY,PDXX,PDZZ,PDZX) RESULT(PGX_M_U)
  USE MODE_GRADIENT_M_PHY, ONLY: GX_M_U_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDXX
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZX
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGX_M_U
  CALL GX_M_U_PHY(D,OFLAT,PY,PDXX,PDZZ,PDZX,PGX_M_U)
END FUNCTION GX_M_U

FUNCTION GY_M_M(OFLAT,PA,PDYY,PDZZ,PDZY) RESULT (PGY_M_M)
  USE MODE_GRADIENT_M_PHY, ONLY: GY_M_M_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDYY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZY
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGY_M_M
  CALL GY_M_M_PHY(D,OFLAT,PA,PDYY,PDZZ,PDZY,PGY_M_M)
END FUNCTION GY_M_M

FUNCTION GY_M_V(OFLAT,PY,PDYY,PDZZ,PDZY) RESULT(PGY_M_V)
  USE MODE_GRADIENT_M_PHY, ONLY: GY_M_V_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDYY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGY_M_V
  CALL GY_M_V_PHY(D,OFLAT,PY,PDYY,PDZZ,PDZY,PGY_M_V)
END FUNCTION GY_M_V

FUNCTION GZ_M_M(PA,PDZZ) RESULT(PGZ_M_M)
  USE MODE_GRADIENT_M_PHY, ONLY: GZ_M_M_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)  :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)  :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGZ_M_M
  CALL GZ_M_M_PHY(D, PA,PDZZ, PGZ_M_M)
END FUNCTION GZ_M_M

FUNCTION GZ_M_W(PY,PDZZ) RESULT(PGZ_M_W)
  USE MODE_GRADIENT_M_PHY, ONLY: GZ_M_W_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGZ_M_W
  CALL GZ_M_W_PHY(D,PY,PDZZ,PGZ_M_W)
END FUNCTION GZ_M_W

FUNCTION GX_U_M(OFLAT,PA,PDXX,PDZZ,PDZX) RESULT(PGX_U_M)
  USE MODE_GRADIENT_U_PHY, ONLY: GX_U_M_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDXX
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZX
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGX_U_M
  CALL GX_U_M_PHY(D,OFLAT,PA,PDXX,PDZZ,PDZX,PGX_U_M)
END FUNCTION GX_U_M

FUNCTION GY_U_UV(OFLAT,PA,PDYY,PDZZ,PDZY) RESULT(PGY_U_UV)
  USE MODE_GRADIENT_U_PHY, ONLY: GY_U_UV_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDYY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZY
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGY_U_UV
  CALL GY_U_UV_PHY(D,OFLAT,PA,PDYY,PDZZ,PDZY,PGY_U_UV)
END FUNCTION GY_U_UV

FUNCTION GZ_U_UW(PA,PDZZ) RESULT(PGZ_U_UW)
  USE MODE_GRADIENT_U_PHY, ONLY: GZ_U_UW_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGZ_U_UW
  CALL GZ_U_UW_PHY(D,PA,PDZZ,PGZ_U_UW)
END FUNCTION GZ_U_UW

FUNCTION GX_V_UV(OFLAT,PA,PDXX,PDZZ,PDZX) RESULT(PGX_V_UV)
  USE MODE_GRADIENT_V_PHY, ONLY: GX_V_UV_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDXX
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZX
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGX_V_UV ! result UV point
  CALL GX_V_UV_PHY(D,OFLAT,PA,PDXX,PDZZ,PDZX,PGX_V_UV)
END FUNCTION GX_V_UV

FUNCTION GY_V_M(OFLAT,PA,PDYY,PDZZ,PDZY) RESULT(PGY_V_M)
  USE MODE_GRADIENT_V_PHY, ONLY: GY_V_M_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDYY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZY
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGY_V_M
  CALL GY_V_M_PHY(D,OFLAT,PA,PDYY,PDZZ,PDZY,PGY_V_M)
END FUNCTION GY_V_M

FUNCTION GZ_V_VW(PA,PDZZ) RESULT(PGZ_V_VW)
  USE MODE_GRADIENT_V_PHY, ONLY: GZ_V_VW_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGZ_V_VW 
  CALL GZ_V_VW_PHY(D,PA,PDZZ,PGZ_V_VW)
END FUNCTION GZ_V_VW

FUNCTION GZ_W_M(PA,PDZZ) RESULT(PGZ_W_M)
  USE MODE_GRADIENT_W_PHY, ONLY: GZ_W_M_PHY
  IMPLICIT NONE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGZ_W_M
  CALL GZ_W_M_PHY(D,PA,PDZZ,PGZ_W_M)
END FUNCTION GZ_W_M

FUNCTION GX_W_UW(OFLAT,PA,PDXX,PDZZ,PDZX) RESULT(PGX_W_UW)
  USE MODE_GRADIENT_W_PHY, ONLY: GX_W_UW_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDXX
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZX
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGX_W_UW
  CALL GX_W_UW_PHY(D,OFLAT,PA,PDXX,PDZZ,PDZX,PGX_W_UW)
END FUNCTION GX_W_UW

FUNCTION GY_W_VW(OFLAT,PA,PDYY,PDZZ,PDZY) RESULT(PGY_W_VW)
  USE MODE_GRADIENT_W_PHY, ONLY: GY_W_VW_PHY
  IMPLICIT NONE
  LOGICAL, INTENT(IN) :: OFLAT
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PA
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDYY
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZZ
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PDZY
  REAL, DIMENSION(D%NIJT,D%NKT) :: PGY_W_VW
  CALL GY_W_VW_PHY(D,OFLAT,PA,PDYY,PDZZ,PDZY,PGY_W_VW)
END FUNCTION GY_W_VW
